<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Tests\Controllers;

use ApimaticAPILib\Controllers\APIValidationExternalApisController;
use ApimaticAPILib\Exceptions;
use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;

class APIValidationExternalApisControllerTest extends BaseTestController
{
    /**
     * @var APIValidationExternalApisController APIValidationExternalApisController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getAPIValidationExternalApisController();
    }

    public function testValidateAPIViaURL()
    {
        // Parameters for the API call
        $descriptionUrl = 'https://petstore.swagger.io/v2/swagger.json';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->validateAPIViaURL($descriptionUrl);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"success":true,"errors":[],"warnings":["Media type <i><code>application/json;' .
                ' charset=utf-8</code></i> content definition of response code <i><code>429</cod' .
                'e></i> in endpoint <i><code>getRealTimeData</code></i> of group <i><code>data</' .
                'code></i> contains an example value with following undeclared fields: <i><code>' .
                'detail</i></code>.","Endpoint <i><code>getRealTimeData</code></i> has an exampl' .
                'e specified for error code <i><code>429</code></i> which contains following und' .
                'eclared fields: <i><code>detail</i></code>.","Media type <i><code>application/j' .
                'son; charset=utf-8</code></i> content definition of response code <i><code>429<' .
                '/code></i> in endpoint <i><code>getDataPerCategory</code></i> of group <i><code' .
                '>data</code></i> contains an example value with following undeclared fields: <i' .
                '><code>detail</i></code>.","Endpoint <i><code>getDataPerCategory</code></i> has' .
                ' an example specified for error code <i><code>429</code></i> which contains fol' .
                'lowing undeclared fields: <i><code>detail</i></code>.","Media type <i><code>app' .
                'lication/json; charset=utf-8</code></i> content definition of response code <i>' .
                '<code>429</code></i> in endpoint <i><code>getData</code></i> of group <i><code>' .
                'data</code></i> contains an example value with following undeclared fields: <i>' .
                '<code>detail</i></code>.","Endpoint <i><code>getData</code></i> has an example ' .
                'specified for error code <i><code>429</code></i> which contains following undec' .
                'lared fields: <i><code>detail</i></code>.","Media type <i><code>application/jso' .
                'n; charset=utf-8</code></i> content definition of response code <i><code>429</c' .
                'ode></i> in endpoint <i><code>getActiveStatuses</code></i> of group <i><code>st' .
                'atuses</code></i> contains an example value with following undeclared fields: <' .
                'i><code>detail</i></code>.","Endpoint <i><code>getActiveStatuses</code></i> has' .
                ' an example specified for error code <i><code>429</code></i> which contains fol' .
                'lowing undeclared fields: <i><code>detail</i></code>.","Media type <i><code>app' .
                'lication/json; charset=utf-8</code></i> content definition of response code <i>' .
                '<code>200</code></i> in endpoint <i><code>getDevices</code></i> of group <i><co' .
                'de>assets</code></i> contains an example value with following undeclared fields' .
                ': <i><code>deviceModelId</code></i>, <i><code>manufacturer</code></i>, <i><code' .
                '>model</i></code>.","Media type <i><code>application/json; charset=utf-8</code>' .
                '</i> content definition of response code <i><code>429</code></i> in endpoint <i' .
                '><code>getDevices</code></i> of group <i><code>assets</code></i> contains an ex' .
                'ample value with following undeclared fields: <i><code>detail</i></code>.","End' .
                'point <i><code>getDevices</code></i> has an example specified for error code <i' .
                '><code>429</code></i> which contains following undeclared fields: <i><code>deta' .
                'il</i></code>.","Media type <i><code>application/json; charset=utf-8</code></i>' .
                ' content definition of response code <i><code>429</code></i> in endpoint <i><co' .
                'de>getAlarms</code></i> of group <i><code>alerts</code></i> contains an example' .
                ' value with following undeclared fields: <i><code>detail</i></code>.","Endpoint' .
                ' <i><code>getAlarms</code></i> has an example specified for error code <i><code' .
                '>429</code></i> which contains following undeclared fields: <i><code>detail</i>' .
                '</code>.","Media type <i><code>application/json; charset=utf-8</code></i> conte' .
                'nt definition of response code <i><code>429</code></i> in endpoint <i><code>get' .
                'ActiveAlerts</code></i> of group <i><code>alerts</code></i> contains an example' .
                ' value with following undeclared fields: <i><code>detail</i></code>.","Endpoint' .
                ' <i><code>getActiveAlerts</code></i> has an example specified for error code <i' .
                '><code>429</code></i> which contains following undeclared fields: <i><code>deta' .
                'il</i></code>.","Media type <i><code>application/json; charset=utf-8</code></i>' .
                ' content definition of response code <i><code>429</code></i> in endpoint <i><co' .
                'de>getAlerts</code></i> of group <i><code>alerts</code></i> contains an example' .
                ' value with following undeclared fields: <i><code>detail</i></code>.","Endpoint' .
                ' <i><code>getAlerts</code></i> has an example specified for error code <i><code' .
                '>429</code></i> which contains following undeclared fields: <i><code>detail</i>' .
                '</code>.","Media type <i><code>application/json; charset=utf-8</code></i> conte' .
                'nt definition of response code <i><code>429</code></i> in endpoint <i><code>get' .
                'Configuration</code></i> of group <i><code>configuration data</code></i> contai' .
                'ns an example value with following undeclared fields: <i><code>detail</i></code' .
                '>.","Endpoint <i><code>getConfiguration</code></i> has an example specified for' .
                ' error code <i><code>429</code></i> which contains following undeclared fields:' .
                ' <i><code>detail</i></code>.","Media type <i><code>application/json; charset=ut' .
                'f-8</code></i> content definition of response code <i><code>429</code></i> in e' .
                'ndpoint <i><code>getActiveAlarms</code></i> of group <i><code>alerts</code></i>' .
                ' contains an example value with following undeclared fields: <i><code>detail</i' .
                '></code>.","Endpoint <i><code>getActiveAlarms</code></i> has an example specifi' .
                'ed for error code <i><code>429</code></i> which contains following undeclared f' .
                'ields: <i><code>detail</i></code>.","Media type <i><code>application/json; char' .
                'set=utf-8</code></i> content definition of response code <i><code>429</code></i' .
                '> in endpoint <i><code>getPowerCurves</code></i> of group <i><code>assets</code' .
                '></i> contains an example value with following undeclared fields: <i><code>deta' .
                'il</i></code>.","Endpoint <i><code>getPowerCurves</code></i> has an example spe' .
                'cified for error code <i><code>429</code></i> which contains following undeclar' .
                'ed fields: <i><code>detail</i></code>.","Media type <i><code>application/json; ' .
                'charset=utf-8</code></i> content definition of response code <i><code>429</code' .
                '></i> in endpoint <i><code>getDataSignals</code></i> of group <i><code>data</co' .
                'de></i> contains an example value with following undeclared fields: <i><code>de' .
                'tail</i></code>.","Endpoint <i><code>getDataSignals</code></i> has an example s' .
                'pecified for error code <i><code>429</code></i> which contains following undecl' .
                'ared fields: <i><code>detail</i></code>.","Media type <i><code>application/json' .
                '; charset=utf-8</code></i> content definition of response code <i><code>429</co' .
                'de></i> in endpoint <i><code>getStatuses</code></i> of group <i><code>statuses<' .
                '/code></i> contains an example value with following undeclared fields: <i><code' .
                '>detail</i></code>.","Endpoint <i><code>getStatuses</code></i> has an example s' .
                'pecified for error code <i><code>429</code></i> which contains following undecl' .
                'ared fields: <i><code>detail</i></code>.","Media type <i><code>application/json' .
                '; charset=utf-8</code></i> content definition of response code <i><code>429</co' .
                'de></i> in endpoint <i><code>getSites</code></i> of group <i><code>assets</code' .
                '></i> contains an example value with following undeclared fields: <i><code>deta' .
                'il</i></code>.","Endpoint <i><code>getSites</code></i> has an example specified' .
                ' for error code <i><code>429</code></i> which contains following undeclared fie' .
                'lds: <i><code>detail</i></code>."],"messages":["One or more elements in the API' .
                ' specification has a missing description field."]}'
            )))
            ->assert();
    }
}
