<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Tests\Controllers;

use ApimaticAPILib\Controllers\TransformationController;
use ApimaticAPILib\Exceptions;

class TransformationControllerTest extends BaseTestController
{
    /**
     * @var TransformationController TransformationController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTransformationController();
    }

    public function testListAllTransformations()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllTransformations();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
