<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Authentication;

use Core\Authentication\CoreAuth;
use Core\Request\Parameters\HeaderParam;
use ApimaticAPILib\CustomHeaderAuthenticationCredentials;

/**
 * Utility class for authorization and token management.
 */
class CustomHeaderAuthenticationManager extends CoreAuth implements CustomHeaderAuthenticationCredentials
{
    private $authorization;

    /**
     * Returns an instance of this class.
     *
     * @param string $authorization Auth Header. Provide your Auth key in the format `X-Auth-Key
     *        {auth-key}`.
     */
    public function __construct(string $authorization)
    {
        parent::__construct(HeaderParam::init('Authorization', $authorization)->required());
        $this->authorization = $authorization;
    }

    /**
     * String value for authorization.
     */
    public function getAuthorization(): string
    {
        return $this->authorization;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Auth Header. Provide your Auth key in the format `X-Auth-Key
     *        {auth-key}`.
     */
    public function equals(string $authorization): bool
    {
        return $authorization == $this->authorization;
    }
}
