<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ApiEntity;
use ApimaticAPILib\Models\Authentication;
use ApimaticAPILib\Models\CodeGenSettings;
use ApimaticAPILib\Models\MetaData;
use ApimaticAPILib\Models\ServerConfiguration;
use ApimaticAPILib\Models\TestGenSettings;
use Core\Utils\CoreHelper;

/**
 * Builder for model ApiEntity
 *
 * @see ApiEntity
 */
class ApiEntityBuilder
{
    /**
     * @var ApiEntity
     */
    private $instance;

    private function __construct(ApiEntity $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new api entity Builder object.
     */
    public static function init(
        string $id,
        string $encryptedId,
        string $apiKey,
        string $apiGroupId,
        string $imageUri,
        string $creationDate,
        bool $public,
        string $name,
        string $description,
        string $version,
        array $additionalHeaders,
        Authentication $authentication,
        CodeGenSettings $codeGenSettings,
        TestGenSettings $testGenSettings,
        array $errors,
        ServerConfiguration $serverConfiguration,
        array $endpointsGroup,
        MetaData $metaData
    ): self {
        return new self(new ApiEntity(
            $id,
            $encryptedId,
            $apiKey,
            $apiGroupId,
            $imageUri,
            $creationDate,
            $public,
            $name,
            $description,
            $version,
            $additionalHeaders,
            $authentication,
            $codeGenSettings,
            $testGenSettings,
            $errors,
            $serverConfiguration,
            $endpointsGroup,
            $metaData
        ));
    }

    /**
     * Initializes a new api entity object.
     */
    public function build(): ApiEntity
    {
        return CoreHelper::clone($this->instance);
    }
}
