<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\APIEntityIdentifier;
use Core\Utils\CoreHelper;

/**
 * Builder for model APIEntityIdentifier
 *
 * @see APIEntityIdentifier
 */
class APIEntityIdentifierBuilder
{
    /**
     * @var APIEntityIdentifier
     */
    private $instance;

    private function __construct(APIEntityIdentifier $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new apientity identifier Builder object.
     */
    public static function init(string $apiEntityId): self
    {
        return new self(new APIEntityIdentifier($apiEntityId));
    }

    /**
     * Initializes a new apientity identifier object.
     */
    public function build(): APIEntityIdentifier
    {
        return CoreHelper::clone($this->instance);
    }
}
