<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\APIEntityCodeGeneration;
use Core\Utils\CoreHelper;

/**
 * Builder for model APIEntityCodeGeneration
 *
 * @see APIEntityCodeGeneration
 */
class APIEntityCodeGenerationBuilder
{
    /**
     * @var APIEntityCodeGeneration
     */
    private $instance;

    private function __construct(APIEntityCodeGeneration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new apientity code generation Builder object.
     */
    public static function init(
        string $id,
        string $template,
        string $generatedFile,
        \DateTime $generatedOn,
        string $hashCode,
        string $codeGenerationSource,
        string $codeGenVersion,
        bool $success,
        string $apiEntityId
    ): self {
        return new self(new APIEntityCodeGeneration(
            $id,
            $template,
            $generatedFile,
            $generatedOn,
            $hashCode,
            $codeGenerationSource,
            $codeGenVersion,
            $success,
            $apiEntityId
        ));
    }

    /**
     * Initializes a new apientity code generation object.
     */
    public function build(): APIEntityCodeGeneration
    {
        return CoreHelper::clone($this->instance);
    }
}
