<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ApiValidationSummary;
use Core\Utils\CoreHelper;

/**
 * Builder for model ApiValidationSummary
 *
 * @see ApiValidationSummary
 */
class ApiValidationSummaryBuilder
{
    /**
     * @var ApiValidationSummary
     */
    private $instance;

    private function __construct(ApiValidationSummary $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new api validation summary Builder object.
     */
    public static function init(bool $success, array $errors, array $warnings, array $messages): self
    {
        return new self(new ApiValidationSummary($success, $errors, $warnings, $messages));
    }

    /**
     * Initializes a new api validation summary object.
     */
    public function build(): ApiValidationSummary
    {
        return CoreHelper::clone($this->instance);
    }
}
