<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\AuthScope;
use Core\Utils\CoreHelper;

/**
 * Builder for model AuthScope
 *
 * @see AuthScope
 */
class AuthScopeBuilder
{
    /**
     * @var AuthScope
     */
    private $instance;

    private function __construct(AuthScope $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new auth scope Builder object.
     */
    public static function init(string $id, string $name, string $value, string $description): self
    {
        return new self(new AuthScope($id, $name, $value, $description));
    }

    /**
     * Initializes a new auth scope object.
     */
    public function build(): AuthScope
    {
        return CoreHelper::clone($this->instance);
    }
}
