<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\Authentication;
use Core\Utils\CoreHelper;

/**
 * Builder for model Authentication
 *
 * @see Authentication
 */
class AuthenticationBuilder
{
    /**
     * @var Authentication
     */
    private $instance;

    private function __construct(Authentication $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new authentication Builder object.
     */
    public static function init(
        string $id,
        string $authType,
        array $scopes,
        array $parameters,
        array $authScopes,
        array $authGrantTypes,
        array $paramFormats
    ): self {
        return new self(
            new Authentication($id, $authType, $scopes, $parameters, $authScopes, $authGrantTypes, $paramFormats)
        );
    }

    /**
     * Initializes a new authentication object.
     */
    public function build(): Authentication
    {
        return CoreHelper::clone($this->instance);
    }
}
