<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\CodeGenSettings;
use Core\Utils\CoreHelper;

/**
 * Builder for model CodeGenSettings
 *
 * @see CodeGenSettings
 */
class CodeGenSettingsBuilder
{
    /**
     * @var CodeGenSettings
     */
    private $instance;

    private function __construct(CodeGenSettings $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new code gen settings Builder object.
     */
    public static function init(
        bool $isAsync,
        bool $useHttpMethodPrefix,
        bool $useModelPrefix,
        bool $useEnumPrefix,
        bool $useConstructorsForConfig,
        bool $useCommonSdkLibrary,
        bool $generateInterfaces,
        bool $generateAppveyorConfig,
        bool $generateCircleConfig,
        bool $generateJenkinsConfig,
        bool $generateTravisConfig,
        bool $androidUseAppManifest,
        bool $iosUseAppInfoPlist,
        bool $iosGenerateCoreData,
        bool $runscopeEnabled,
        bool $collapseParamsToArray,
        bool $preserveParameterOrder,
        bool $appendContentHeaders,
        bool $modelSerializationIsJSON,
        bool $nullify404,
        bool $validateRequiredParameters,
        bool $enableAdditionalModelProperties,
        bool $javaUsePropertiesConfig,
        bool $useControllerPrefix,
        bool $useExceptionPrefix,
        string $parameterArrayFormat,
        string $objCHttpClient,
        string $cSharpHttpClient,
        string $androidHttpClient,
        string $nodeHttpClient,
        string $phpHttpClient,
        int $bodySerialization,
        string $arraySerialization,
        int $timeout,
        bool $enableLogging,
        bool $enableHttpCache,
        int $retries,
        int $retryInterval,
        bool $generateAdvancedDocs,
        bool $storeTimezoneInformation,
        bool $enablePhpComposerVersionString,
        array $securityProtocols,
        bool $underscoreNumbers,
        bool $useSingletonPattern,
        bool $disableLinting,
        bool $allowSkippingSSLCertVerification,
        array $applyCustomizations,
        array $doNotSplitWords,
        bool $sortResources,
        bool $enableGlobalUserAgent
    ): self {
        return new self(new CodeGenSettings(
            $isAsync,
            $useHttpMethodPrefix,
            $useModelPrefix,
            $useEnumPrefix,
            $useConstructorsForConfig,
            $useCommonSdkLibrary,
            $generateInterfaces,
            $generateAppveyorConfig,
            $generateCircleConfig,
            $generateJenkinsConfig,
            $generateTravisConfig,
            $androidUseAppManifest,
            $iosUseAppInfoPlist,
            $iosGenerateCoreData,
            $runscopeEnabled,
            $collapseParamsToArray,
            $preserveParameterOrder,
            $appendContentHeaders,
            $modelSerializationIsJSON,
            $nullify404,
            $validateRequiredParameters,
            $enableAdditionalModelProperties,
            $javaUsePropertiesConfig,
            $useControllerPrefix,
            $useExceptionPrefix,
            $parameterArrayFormat,
            $objCHttpClient,
            $cSharpHttpClient,
            $androidHttpClient,
            $nodeHttpClient,
            $phpHttpClient,
            $bodySerialization,
            $arraySerialization,
            $timeout,
            $enableLogging,
            $enableHttpCache,
            $retries,
            $retryInterval,
            $generateAdvancedDocs,
            $storeTimezoneInformation,
            $enablePhpComposerVersionString,
            $securityProtocols,
            $underscoreNumbers,
            $useSingletonPattern,
            $disableLinting,
            $allowSkippingSSLCertVerification,
            $applyCustomizations,
            $doNotSplitWords,
            $sortResources,
            $enableGlobalUserAgent
        ));
    }

    /**
     * Initializes a new code gen settings object.
     */
    public function build(): CodeGenSettings
    {
        return CoreHelper::clone($this->instance);
    }
}
