<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\CodeGeneration;
use Core\Utils\CoreHelper;

/**
 * Builder for model CodeGeneration
 *
 * @see CodeGeneration
 */
class CodeGenerationBuilder
{
    /**
     * @var CodeGeneration
     */
    private $instance;

    private function __construct(CodeGeneration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new code generation Builder object.
     */
    public static function init(
        string $id,
        string $template,
        string $generatedFile,
        \DateTime $generatedOn,
        string $hashCode,
        string $codeGenerationSource,
        string $codeGenVersion,
        bool $success
    ): self {
        return new self(new CodeGeneration(
            $id,
            $template,
            $generatedFile,
            $generatedOn,
            $hashCode,
            $codeGenerationSource,
            $codeGenVersion,
            $success
        ));
    }

    /**
     * Initializes a new code generation object.
     */
    public function build(): CodeGeneration
    {
        return CoreHelper::clone($this->instance);
    }
}
