<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\DocsValidationSummary;
use Core\Utils\CoreHelper;

/**
 * Builder for model DocsValidationSummary
 *
 * @see DocsValidationSummary
 */
class DocsValidationSummaryBuilder
{
    /**
     * @var DocsValidationSummary
     */
    private $instance;

    private function __construct(DocsValidationSummary $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new docs validation summary Builder object.
     */
    public static function init(bool $success, array $errors, array $warnings, array $messages): self
    {
        return new self(new DocsValidationSummary($success, $errors, $warnings, $messages));
    }

    /**
     * Initializes a new docs validation summary object.
     */
    public function build(): DocsValidationSummary
    {
        return CoreHelper::clone($this->instance);
    }
}
