<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\EndpointsGroup;
use Core\Utils\CoreHelper;

/**
 * Builder for model EndpointsGroup
 *
 * @see EndpointsGroup
 */
class EndpointsGroupBuilder
{
    /**
     * @var EndpointsGroup
     */
    private $instance;

    private function __construct(EndpointsGroup $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new endpoints group Builder object.
     */
    public static function init(string $name, string $description): self
    {
        return new self(new EndpointsGroup($name, $description));
    }

    /**
     * Initializes a new endpoints group object.
     */
    public function build(): EndpointsGroup
    {
        return CoreHelper::clone($this->instance);
    }
}
