<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\Environment;
use Core\Utils\CoreHelper;

/**
 * Builder for model Environment
 *
 * @see Environment
 */
class EnvironmentBuilder
{
    /**
     * @var Environment
     */
    private $instance;

    private function __construct(Environment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new environment Builder object.
     */
    public static function init(string $id, string $name, array $servers): self
    {
        return new self(new Environment($id, $name, $servers));
    }

    /**
     * Initializes a new environment object.
     */
    public function build(): Environment
    {
        return CoreHelper::clone($this->instance);
    }
}
