<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\Attributes;
use ApimaticAPILib\Models\Field;
use Core\Utils\CoreHelper;

/**
 * Builder for model Field
 *
 * @see Field
 */
class FieldBuilder
{
    /**
     * @var Field
     */
    private $instance;

    private function __construct(Field $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new field Builder object.
     */
    public static function init(
        bool $optional,
        string $type,
        bool $constant,
        bool $isArray,
        bool $isStream,
        bool $isAttribute,
        bool $isMap,
        Attributes $attributes,
        bool $nullable,
        string $id,
        string $name,
        string $description,
        string $defaultValue
    ): self {
        return new self(new Field(
            $optional,
            $type,
            $constant,
            $isArray,
            $isStream,
            $isAttribute,
            $isMap,
            $attributes,
            $nullable,
            $id,
            $name,
            $description,
            $defaultValue
        ));
    }

    /**
     * Initializes a new field object.
     */
    public function build(): Field
    {
        return CoreHelper::clone($this->instance);
    }
}
