<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\GenerateSDKViaFileRequestBody;
use Core\Utils\CoreHelper;

/**
 * Builder for model GenerateSDKViaFileRequestBody
 *
 * @see GenerateSDKViaFileRequestBody
 */
class GenerateSDKViaFileRequestBodyBuilder
{
    /**
     * @var GenerateSDKViaFileRequestBody
     */
    private $instance;

    private function __construct(GenerateSDKViaFileRequestBody $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new generate sdkvia file request body Builder object.
     */
    public static function init(string $file, string $template): self
    {
        return new self(new GenerateSDKViaFileRequestBody($file, $template));
    }

    /**
     * Initializes a new generate sdkvia file request body object.
     */
    public function build(): GenerateSDKViaFileRequestBody
    {
        return CoreHelper::clone($this->instance);
    }
}
