<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\GenerateSdkViaUrlRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model GenerateSdkViaUrlRequest
 *
 * @see GenerateSdkViaUrlRequest
 */
class GenerateSdkViaUrlRequestBuilder
{
    /**
     * @var GenerateSdkViaUrlRequest
     */
    private $instance;

    private function __construct(GenerateSdkViaUrlRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new generate sdk via url request Builder object.
     */
    public static function init(string $url, string $template): self
    {
        return new self(new GenerateSdkViaUrlRequest($url, $template));
    }

    /**
     * Initializes a new generate sdk via url request object.
     */
    public function build(): GenerateSdkViaUrlRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
