<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ImportValidationSummary;
use Core\Utils\CoreHelper;

/**
 * Builder for model ImportValidationSummary
 *
 * @see ImportValidationSummary
 */
class ImportValidationSummaryBuilder
{
    /**
     * @var ImportValidationSummary
     */
    private $instance;

    private function __construct(ImportValidationSummary $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new import validation summary Builder object.
     */
    public static function init(bool $success, array $errors, array $warnings, array $messages): self
    {
        return new self(new ImportValidationSummary($success, $errors, $warnings, $messages));
    }

    /**
     * Initializes a new import validation summary object.
     */
    public function build(): ImportValidationSummary
    {
        return CoreHelper::clone($this->instance);
    }
}
