<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ImportApiViaUrlRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model ImportApiViaUrlRequest
 *
 * @see ImportApiViaUrlRequest
 */
class ImportApiViaUrlRequestBuilder
{
    /**
     * @var ImportApiViaUrlRequest
     */
    private $instance;

    private function __construct(ImportApiViaUrlRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new import api via url request Builder object.
     */
    public static function init(string $url): self
    {
        return new self(new ImportApiViaUrlRequest($url));
    }

    /**
     * Initializes a new import api via url request object.
     */
    public function build(): ImportApiViaUrlRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
