<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ImportNewAPIVersionViaFileRequestBody;
use Core\Utils\CoreHelper;

/**
 * Builder for model ImportNewAPIVersionViaFileRequestBody
 *
 * @see ImportNewAPIVersionViaFileRequestBody
 */
class ImportNewAPIVersionViaFileRequestBodyBuilder
{
    /**
     * @var ImportNewAPIVersionViaFileRequestBody
     */
    private $instance;

    private function __construct(ImportNewAPIVersionViaFileRequestBody $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new import new apiversion via file request body Builder object.
     */
    public static function init(string $versionOverride, string $file): self
    {
        return new self(new ImportNewAPIVersionViaFileRequestBody($versionOverride, $file));
    }

    /**
     * Initializes a new import new apiversion via file request body object.
     */
    public function build(): ImportNewAPIVersionViaFileRequestBody
    {
        return CoreHelper::clone($this->instance);
    }
}
