<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\InplaceImportApiViaUrlRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model InplaceImportApiViaUrlRequest
 *
 * @see InplaceImportApiViaUrlRequest
 */
class InplaceImportApiViaUrlRequestBuilder
{
    /**
     * @var InplaceImportApiViaUrlRequest
     */
    private $instance;

    private function __construct(InplaceImportApiViaUrlRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new inplace import api via url request Builder object.
     */
    public static function init(string $url): self
    {
        return new self(new InplaceImportApiViaUrlRequest($url));
    }

    /**
     * Initializes a new inplace import api via url request object.
     */
    public function build(): InplaceImportApiViaUrlRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
