<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\InplaceApiImportBinaryFile;
use Core\Utils\CoreHelper;

/**
 * Builder for model InplaceApiImportBinaryFile
 *
 * @see InplaceApiImportBinaryFile
 */
class InplaceApiImportBinaryFileBuilder
{
    /**
     * @var InplaceApiImportBinaryFile
     */
    private $instance;

    private function __construct(InplaceApiImportBinaryFile $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new inplace api import binary file Builder object.
     */
    public static function init(string $file): self
    {
        return new self(new InplaceApiImportBinaryFile($file));
    }

    /**
     * Initializes a new inplace api import binary file object.
     */
    public function build(): InplaceApiImportBinaryFile
    {
        return CoreHelper::clone($this->instance);
    }
}
