<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ApiValidationSummary;
use ApimaticAPILib\Models\DocsValidationSummary;
use ApimaticAPILib\Models\ImportValidationSummary;
use ApimaticAPILib\Models\MetaData;
use Core\Utils\CoreHelper;

/**
 * Builder for model MetaData
 *
 * @see MetaData
 */
class MetaDataBuilder
{
    /**
     * @var MetaData
     */
    private $instance;

    private function __construct(MetaData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new meta data Builder object.
     */
    public static function init(
        ImportValidationSummary $importValidationSummary,
        ApiValidationSummary $apiValidationSummary,
        DocsValidationSummary $docsValidationSummary
    ): self {
        return new self(new MetaData($importValidationSummary, $apiValidationSummary, $docsValidationSummary));
    }

    /**
     * Initializes a new meta data object.
     */
    public function build(): MetaData
    {
        return CoreHelper::clone($this->instance);
    }
}
