<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\Attributes;
use ApimaticAPILib\Models\Parameter;
use Core\Utils\CoreHelper;

/**
 * Builder for model Parameter
 *
 * @see Parameter
 */
class ParameterBuilder
{
    /**
     * @var Parameter
     */
    private $instance;

    private function __construct(Parameter $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new parameter Builder object.
     */
    public static function init(
        bool $optional,
        string $type,
        bool $constant,
        bool $isArray,
        bool $isStream,
        bool $isAttribute,
        bool $isMap,
        Attributes $attributes,
        bool $nullable,
        string $id,
        string $name,
        string $description,
        string $defaultValue,
        string $paramFormat
    ): self {
        return new self(new Parameter(
            $optional,
            $type,
            $constant,
            $isArray,
            $isStream,
            $isAttribute,
            $isMap,
            $attributes,
            $nullable,
            $id,
            $name,
            $description,
            $defaultValue,
            $paramFormat
        ));
    }

    /**
     * Initializes a new parameter object.
     */
    public function build(): Parameter
    {
        return CoreHelper::clone($this->instance);
    }
}
