<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ParamterFormatDetails;
use Core\Utils\CoreHelper;

/**
 * Builder for model ParamterFormatDetails
 *
 * @see ParamterFormatDetails
 */
class ParamterFormatDetailsBuilder
{
    /**
     * @var ParamterFormatDetails
     */
    private $instance;

    private function __construct(ParamterFormatDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new paramter format details Builder object.
     */
    public static function init(string $paramFormat): self
    {
        return new self(new ParamterFormatDetails($paramFormat));
    }

    /**
     * Initializes a new paramter format details object.
     */
    public function build(): ParamterFormatDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
