<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\PlatformsTemplate;
use Core\Utils\CoreHelper;

/**
 * Builder for model PlatformsTemplate
 *
 * @see PlatformsTemplate
 */
class PlatformsTemplateBuilder
{
    /**
     * @var PlatformsTemplate
     */
    private $instance;

    private function __construct(PlatformsTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new platforms template Builder object.
     */
    public static function init(string $template): self
    {
        return new self(new PlatformsTemplate($template));
    }

    /**
     * Initializes a new platforms template object.
     */
    public function build(): PlatformsTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
