<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ServerConfiguration;
use Core\Utils\CoreHelper;

/**
 * Builder for model ServerConfiguration
 *
 * @see ServerConfiguration
 */
class ServerConfigurationBuilder
{
    /**
     * @var ServerConfiguration
     */
    private $instance;

    private function __construct(ServerConfiguration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new server configuration Builder object.
     */
    public static function init(
        string $id,
        string $defaultEnvironment,
        string $defaultServer,
        array $environments,
        array $parameters
    ): self {
        return new self(
            new ServerConfiguration($id, $defaultEnvironment, $defaultServer, $environments, $parameters)
        );
    }

    /**
     * Initializes a new server configuration object.
     */
    public function build(): ServerConfiguration
    {
        return CoreHelper::clone($this->instance);
    }
}
