<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\Server;
use Core\Utils\CoreHelper;

/**
 * Builder for model Server
 *
 * @see Server
 */
class ServerBuilder
{
    /**
     * @var Server
     */
    private $instance;

    private function __construct(Server $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new server Builder object.
     */
    public static function init(string $id, string $name, string $url): self
    {
        return new self(new Server($id, $name, $url));
    }

    /**
     * Initializes a new server object.
     */
    public function build(): Server
    {
        return CoreHelper::clone($this->instance);
    }
}
