<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\TestGenSettings;
use Core\Utils\CoreHelper;

/**
 * Builder for model TestGenSettings
 *
 * @see TestGenSettings
 */
class TestGenSettingsBuilder
{
    /**
     * @var TestGenSettings
     */
    private $instance;

    private function __construct(TestGenSettings $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new test gen settings Builder object.
     */
    public static function init(float $precisionDelta, int $testTimeout, array $configuration): self
    {
        return new self(new TestGenSettings($precisionDelta, $testTimeout, $configuration));
    }

    /**
     * Initializes a new test gen settings object.
     */
    public function build(): TestGenSettings
    {
        return CoreHelper::clone($this->instance);
    }
}
