<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\ApiValidationSummary;
use ApimaticAPILib\Models\Transformation;
use Core\Utils\CoreHelper;

/**
 * Builder for model Transformation
 *
 * @see Transformation
 */
class TransformationBuilder
{
    /**
     * @var Transformation
     */
    private $instance;

    private function __construct(Transformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transformation Builder object.
     */
    public static function init(
        string $id,
        string $transformedOn,
        string $userId,
        string $inputtedFile,
        string $generatedFile,
        string $exportFormat,
        string $transformationSource,
        string $transformationInput,
        string $codeGenVersion,
        bool $success,
        ApiValidationSummary $importSummary,
        ApiValidationSummary $apiValidationSummary
    ): self {
        return new self(new Transformation(
            $id,
            $transformedOn,
            $userId,
            $inputtedFile,
            $generatedFile,
            $exportFormat,
            $transformationSource,
            $transformationInput,
            $codeGenVersion,
            $success,
            $importSummary,
            $apiValidationSummary
        ));
    }

    /**
     * Initializes a new transformation object.
     */
    public function build(): Transformation
    {
        return CoreHelper::clone($this->instance);
    }
}
