<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\TransformViaFileRequestBody;
use Core\Utils\CoreHelper;

/**
 * Builder for model TransformViaFileRequestBody
 *
 * @see TransformViaFileRequestBody
 */
class TransformViaFileRequestBodyBuilder
{
    /**
     * @var TransformViaFileRequestBody
     */
    private $instance;

    private function __construct(TransformViaFileRequestBody $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transform via file request body Builder object.
     */
    public static function init(string $file, string $exportFormat): self
    {
        return new self(new TransformViaFileRequestBody($file, $exportFormat));
    }

    /**
     * Initializes a new transform via file request body object.
     */
    public function build(): TransformViaFileRequestBody
    {
        return CoreHelper::clone($this->instance);
    }
}
