<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\TransformViaUrlRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model TransformViaUrlRequest
 *
 * @see TransformViaUrlRequest
 */
class TransformViaUrlRequestBuilder
{
    /**
     * @var TransformViaUrlRequest
     */
    private $instance;

    private function __construct(TransformViaUrlRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transform via url request Builder object.
     */
    public static function init(string $url, string $exportFormat): self
    {
        return new self(new TransformViaUrlRequest($url, $exportFormat));
    }

    /**
     * Initializes a new transform via url request object.
     */
    public function build(): TransformViaUrlRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
