<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\UserCodeGenerationRequirements;
use Core\Utils\CoreHelper;

/**
 * Builder for model UserCodeGenerationRequirements
 *
 * @see UserCodeGenerationRequirements
 */
class UserCodeGenerationRequirementsBuilder
{
    /**
     * @var UserCodeGenerationRequirements
     */
    private $instance;

    private function __construct(UserCodeGenerationRequirements $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new user code generation requirements Builder object.
     */
    public static function init(string $userId, string $inputFile): self
    {
        return new self(new UserCodeGenerationRequirements($userId, $inputFile));
    }

    /**
     * Initializes a new user code generation requirements object.
     */
    public function build(): UserCodeGenerationRequirements
    {
        return CoreHelper::clone($this->instance);
    }
}
