<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models\Builders;

use ApimaticAPILib\Models\UserCodeGeneration;
use Core\Utils\CoreHelper;

/**
 * Builder for model UserCodeGeneration
 *
 * @see UserCodeGeneration
 */
class UserCodeGenerationBuilder
{
    /**
     * @var UserCodeGeneration
     */
    private $instance;

    private function __construct(UserCodeGeneration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new user code generation Builder object.
     */
    public static function init(
        string $id,
        string $template,
        string $generatedFile,
        \DateTime $generatedOn,
        string $hashCode,
        string $codeGenerationSource,
        string $codeGenVersion,
        bool $success,
        string $userId,
        string $inputFile
    ): self {
        return new self(new UserCodeGeneration(
            $id,
            $template,
            $generatedFile,
            $generatedOn,
            $hashCode,
            $codeGenerationSource,
            $codeGenVersion,
            $success,
            $userId,
            $inputFile
        ));
    }

    /**
     * Initializes a new user code generation object.
     */
    public function build(): UserCodeGeneration
    {
        return CoreHelper::clone($this->instance);
    }
}
