<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use stdClass;

class APIEntityIdentifier implements \JsonSerializable
{
    /**
     * @var string
     */
    private $apiEntityId;

    /**
     * @param string $apiEntityId
     */
    public function __construct(string $apiEntityId)
    {
        $this->apiEntityId = $apiEntityId;
    }

    /**
     * Returns Api Entity Id.
     * Unique API Entity Identifier
     */
    public function getApiEntityId(): string
    {
        return $this->apiEntityId;
    }

    /**
     * Sets Api Entity Id.
     * Unique API Entity Identifier
     *
     * @required
     * @maps apiEntityId
     */
    public function setApiEntityId(string $apiEntityId): void
    {
        $this->apiEntityId = $apiEntityId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['apiEntityId'] = $this->apiEntityId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
