<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use ApimaticAPILib\Utils\DateTimeHelper;
use stdClass;

/**
 * The Code Generation structure encapsulates all the  the details of an SDK generation performed
 * against an API Entity
 */
class APIEntityCodeGeneration implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $template;

    /**
     * @var string
     */
    private $generatedFile;

    /**
     * @var \DateTime
     */
    private $generatedOn;

    /**
     * @var string
     */
    private $hashCode;

    /**
     * @var string
     */
    private $codeGenerationSource;

    /**
     * @var string
     */
    private $codeGenVersion;

    /**
     * @var bool
     */
    private $success;

    /**
     * @var string
     */
    private $apiEntityId;

    /**
     * @param string $id
     * @param string $template
     * @param string $generatedFile
     * @param \DateTime $generatedOn
     * @param string $hashCode
     * @param string $codeGenerationSource
     * @param string $codeGenVersion
     * @param bool $success
     * @param string $apiEntityId
     */
    public function __construct(
        string $id,
        string $template,
        string $generatedFile,
        \DateTime $generatedOn,
        string $hashCode,
        string $codeGenerationSource,
        string $codeGenVersion,
        bool $success,
        string $apiEntityId
    ) {
        $this->id = $id;
        $this->template = $template;
        $this->generatedFile = $generatedFile;
        $this->generatedOn = $generatedOn;
        $this->hashCode = $hashCode;
        $this->codeGenerationSource = $codeGenerationSource;
        $this->codeGenVersion = $codeGenVersion;
        $this->success = $success;
        $this->apiEntityId = $apiEntityId;
    }

    /**
     * Returns Id.
     * Unique Code Generation Identifier
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Unique Code Generation Identifier
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Template.
     * The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in.
     */
    public function getTemplate(): string
    {
        return $this->template;
    }

    /**
     * Sets Template.
     * The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in.
     *
     * @required
     * @maps template
     * @factory \ApimaticAPILib\Models\Platforms::checkValue
     */
    public function setTemplate(string $template): void
    {
        $this->template = $template;
    }

    /**
     * Returns Generated File.
     * The generated SDK
     */
    public function getGeneratedFile(): string
    {
        return $this->generatedFile;
    }

    /**
     * Sets Generated File.
     * The generated SDK
     *
     * @required
     * @maps generatedFile
     */
    public function setGeneratedFile(string $generatedFile): void
    {
        $this->generatedFile = $generatedFile;
    }

    /**
     * Returns Generated On.
     * Generation Date and Time
     */
    public function getGeneratedOn(): \DateTime
    {
        return $this->generatedOn;
    }

    /**
     * Sets Generated On.
     * Generation Date and Time
     *
     * @required
     * @maps generatedOn
     * @factory \ApimaticAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setGeneratedOn(\DateTime $generatedOn): void
    {
        $this->generatedOn = $generatedOn;
    }

    /**
     * Returns Hash Code.
     * The md5 hash of the API Description
     */
    public function getHashCode(): string
    {
        return $this->hashCode;
    }

    /**
     * Sets Hash Code.
     * The md5 hash of the API Description
     *
     * @required
     * @maps hashCode
     */
    public function setHashCode(string $hashCode): void
    {
        $this->hashCode = $hashCode;
    }

    /**
     * Returns Code Generation Source.
     * Generation Source
     */
    public function getCodeGenerationSource(): string
    {
        return $this->codeGenerationSource;
    }

    /**
     * Sets Code Generation Source.
     * Generation Source
     *
     * @required
     * @maps codeGenerationSource
     */
    public function setCodeGenerationSource(string $codeGenerationSource): void
    {
        $this->codeGenerationSource = $codeGenerationSource;
    }

    /**
     * Returns Code Gen Version.
     * Generation Version
     */
    public function getCodeGenVersion(): string
    {
        return $this->codeGenVersion;
    }

    /**
     * Sets Code Gen Version.
     * Generation Version
     *
     * @required
     * @maps codeGenVersion
     */
    public function setCodeGenVersion(string $codeGenVersion): void
    {
        $this->codeGenVersion = $codeGenVersion;
    }

    /**
     * Returns Success.
     * Generation Status
     */
    public function getSuccess(): bool
    {
        return $this->success;
    }

    /**
     * Sets Success.
     * Generation Status
     *
     * @required
     * @maps success
     */
    public function setSuccess(bool $success): void
    {
        $this->success = $success;
    }

    /**
     * Returns Api Entity Id.
     * Unique API Entity Identifier
     */
    public function getApiEntityId(): string
    {
        return $this->apiEntityId;
    }

    /**
     * Sets Api Entity Id.
     * Unique API Entity Identifier
     *
     * @required
     * @maps apiEntityId
     */
    public function setApiEntityId(string $apiEntityId): void
    {
        $this->apiEntityId = $apiEntityId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']                   = $this->id;
        $json['template']             = Platforms::checkValue($this->template);
        $json['generatedFile']        = $this->generatedFile;
        $json['generatedOn']          = DateTimeHelper::toRfc3339DateTime($this->generatedOn);
        $json['hashCode']             = $this->hashCode;
        $json['codeGenerationSource'] = $this->codeGenerationSource;
        $json['codeGenVersion']       = $this->codeGenVersion;
        $json['success']              = $this->success;
        $json['apiEntityId']          = $this->apiEntityId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
