<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The structure contains API specification formats that Transformer can convert to.
 */
class ExportFormats
{
    public const APIMATIC = 'APIMATIC';

    public const WADL2009 = 'WADL2009';

    public const WSDL = 'WSDL';

    public const SWAGGER10 = 'Swagger10';

    public const SWAGGER20 = 'Swagger20';

    public const SWAGGERYAML = 'SwaggerYaml';

    /**
     * OpenAPI v3.0 (JSON)
     */
    public const OAS3 = 'OpenApi3Json';

    public const OPENAPI3YAML = 'OpenApi3Yaml';

    public const APIBLUEPRINT = 'APIBluePrint';

    public const RAML = 'RAML';

    public const RAML10 = 'RAML10';

    public const POSTMAN10 = 'Postman10';

    public const POSTMAN20 = 'Postman20';

    public const GRAPHQLSCHEMA = 'GraphQlSchema';

    private const _ALL_VALUES = [
        self::APIMATIC,
        self::WADL2009,
        self::WSDL,
        self::SWAGGER10,
        self::SWAGGER20,
        self::SWAGGERYAML,
        self::OAS3,
        self::OPENAPI3YAML,
        self::APIBLUEPRINT,
        self::RAML,
        self::RAML10,
        self::POSTMAN10,
        self::POSTMAN20,
        self::GRAPHQLSCHEMA
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ExportFormats.");
    }
}
