<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use stdClass;

class ImportNewAPIVersionViaFileRequestBody implements \JsonSerializable
{
    /**
     * @var string
     */
    private $versionOverride;

    /**
     * @var string
     */
    private $file;

    /**
     * @param string $versionOverride
     * @param string $file
     */
    public function __construct(string $versionOverride, string $file)
    {
        $this->versionOverride = $versionOverride;
        $this->file = $file;
    }

    /**
     * Returns Version Override.
     * The version number with which the new API version will be imported. This version number will
     * override the version specified in the API specification file.<br>APIMatic recommends versioning the
     * API with the [versioning scheme](https://docs.apimatic.io/define-apis/basic-settings/#version)
     * documented in the docs.
     */
    public function getVersionOverride(): string
    {
        return $this->versionOverride;
    }

    /**
     * Sets Version Override.
     * The version number with which the new API version will be imported. This version number will
     * override the version specified in the API specification file.<br>APIMatic recommends versioning the
     * API with the [versioning scheme](https://docs.apimatic.io/define-apis/basic-settings/#version)
     * documented in the docs.
     *
     * @required
     * @maps version_override
     */
    public function setVersionOverride(string $versionOverride): void
    {
        $this->versionOverride = $versionOverride;
    }

    /**
     * Returns File.
     * The API specification file.<br>The type of the specification file should be any of the [supported
     * formats](https://docs.apimatic.io/api-transformer/overview-transformer#supported-input-formats).
     */
    public function getFile(): string
    {
        return $this->file;
    }

    /**
     * Sets File.
     * The API specification file.<br>The type of the specification file should be any of the [supported
     * formats](https://docs.apimatic.io/api-transformer/overview-transformer#supported-input-formats).
     *
     * @required
     * @maps file
     */
    public function setFile(string $file): void
    {
        $this->file = $file;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['version_override'] = $this->versionOverride;
        $json['file']             = $this->file;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
