<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use stdClass;

class MetaData implements \JsonSerializable
{
    /**
     * @var ImportValidationSummary
     */
    private $importValidationSummary;

    /**
     * @var ApiValidationSummary
     */
    private $apiValidationSummary;

    /**
     * @var DocsValidationSummary
     */
    private $docsValidationSummary;

    /**
     * @param ImportValidationSummary $importValidationSummary
     * @param ApiValidationSummary $apiValidationSummary
     * @param DocsValidationSummary $docsValidationSummary
     */
    public function __construct(
        ImportValidationSummary $importValidationSummary,
        ApiValidationSummary $apiValidationSummary,
        DocsValidationSummary $docsValidationSummary
    ) {
        $this->importValidationSummary = $importValidationSummary;
        $this->apiValidationSummary = $apiValidationSummary;
        $this->docsValidationSummary = $docsValidationSummary;
    }

    /**
     * Returns Import Validation Summary.
     */
    public function getImportValidationSummary(): ImportValidationSummary
    {
        return $this->importValidationSummary;
    }

    /**
     * Sets Import Validation Summary.
     *
     * @required
     * @maps importValidationSummary
     */
    public function setImportValidationSummary(ImportValidationSummary $importValidationSummary): void
    {
        $this->importValidationSummary = $importValidationSummary;
    }

    /**
     * Returns Api Validation Summary.
     */
    public function getApiValidationSummary(): ApiValidationSummary
    {
        return $this->apiValidationSummary;
    }

    /**
     * Sets Api Validation Summary.
     *
     * @required
     * @maps apiValidationSummary
     */
    public function setApiValidationSummary(ApiValidationSummary $apiValidationSummary): void
    {
        $this->apiValidationSummary = $apiValidationSummary;
    }

    /**
     * Returns Docs Validation Summary.
     */
    public function getDocsValidationSummary(): DocsValidationSummary
    {
        return $this->docsValidationSummary;
    }

    /**
     * Sets Docs Validation Summary.
     *
     * @required
     * @maps docsValidationSummary
     */
    public function setDocsValidationSummary(DocsValidationSummary $docsValidationSummary): void
    {
        $this->docsValidationSummary = $docsValidationSummary;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['importValidationSummary'] = $this->importValidationSummary;
        $json['apiValidationSummary']    = $this->apiValidationSummary;
        $json['docsValidationSummary']   = $this->docsValidationSummary;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
