<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use stdClass;

class ParamterFormatDetails implements \JsonSerializable
{
    /**
     * @var string
     */
    private $paramFormat;

    /**
     * @param string $paramFormat
     */
    public function __construct(string $paramFormat)
    {
        $this->paramFormat = $paramFormat;
    }

    /**
     * Returns Param Format.
     * Specify Parameter Format
     */
    public function getParamFormat(): string
    {
        return $this->paramFormat;
    }

    /**
     * Sets Param Format.
     * Specify Parameter Format
     *
     * @required
     * @maps ParamFormat
     */
    public function setParamFormat(string $paramFormat): void
    {
        $this->paramFormat = $paramFormat;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['ParamFormat'] = $this->paramFormat;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
