<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in.
 */
class Platforms
{
    /**
     * .NET Standard Library
     */
    public const CS_NET_STANDARD_LIB = 'CS_NET_STANDARD_LIB';

    /**
     * JAVA
     */
    public const JAVA_ECLIPSE_JRE_LIB = 'JAVA_ECLIPSE_JRE_LIB';

    /**
     * PHP
     */
    public const PHP_GENERIC_LIB_V2 = 'PHP_GENERIC_LIB';

    /**
     * Python
     */
    public const PYTHON_GENERIC_LIB = 'PYTHON_GENERIC_LIB';

    /**
     * Ruby
     */
    public const RUBY_GENERIC_LIB = 'RUBY_GENERIC_LIB';

    /**
     * Typescript
     */
    public const TS_GENERIC_LIB = 'TS_GENERIC_LIB';

    /**
     * Go
     */
    public const GO_GENERIC_LIB = 'GO_GENERIC_LIB';

    private const _ALL_VALUES = [
        self::CS_NET_STANDARD_LIB,
        self::JAVA_ECLIPSE_JRE_LIB,
        self::PHP_GENERIC_LIB_V2,
        self::PYTHON_GENERIC_LIB,
        self::RUBY_GENERIC_LIB,
        self::TS_GENERIC_LIB,
        self::GO_GENERIC_LIB
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Platforms.");
    }
}
