<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use stdClass;

class PlatformsTemplate implements \JsonSerializable
{
    /**
     * @var string
     */
    private $template;

    /**
     * @param string $template
     */
    public function __construct(string $template)
    {
        $this->template = $template;
    }

    /**
     * Returns Template.
     * The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in.
     */
    public function getTemplate(): string
    {
        return $this->template;
    }

    /**
     * Sets Template.
     * The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in.
     *
     * @required
     * @maps template
     * @factory \ApimaticAPILib\Models\Platforms::checkValue
     */
    public function setTemplate(string $template): void
    {
        $this->template = $template;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['template'] = Platforms::checkValue($this->template);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
