<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use stdClass;

class TransformViaFileRequestBody implements \JsonSerializable
{
    /**
     * @var string
     */
    private $file;

    /**
     * @var string
     */
    private $exportFormat;

    /**
     * @param string $file
     * @param string $exportFormat
     */
    public function __construct(string $file, string $exportFormat)
    {
        $this->file = $file;
        $this->exportFormat = $exportFormat;
    }

    /**
     * Returns File.
     * The API specification file.<br>The type of the specification file should be any of the [supported
     * formats](https://docs.apimatic.io/api-transformer/overview-transformer#supported-input-formats).
     */
    public function getFile(): string
    {
        return $this->file;
    }

    /**
     * Sets File.
     * The API specification file.<br>The type of the specification file should be any of the [supported
     * formats](https://docs.apimatic.io/api-transformer/overview-transformer#supported-input-formats).
     *
     * @required
     * @maps file
     */
    public function setFile(string $file): void
    {
        $this->file = $file;
    }

    /**
     * Returns Export Format.
     * The structure contains API specification formats that Transformer can convert to.
     */
    public function getExportFormat(): string
    {
        return $this->exportFormat;
    }

    /**
     * Sets Export Format.
     * The structure contains API specification formats that Transformer can convert to.
     *
     * @required
     * @maps export_format
     * @factory \ApimaticAPILib\Models\ExportFormats::checkValue
     */
    public function setExportFormat(string $exportFormat): void
    {
        $this->exportFormat = $exportFormat;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['file']          = $this->file;
        $json['export_format'] = ExportFormats::checkValue($this->exportFormat);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
