<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib\Models;

use stdClass;

/**
 * This structure puts together the URL of the file to be transformed, along with the desired export
 * format.
 */
class TransformViaUrlRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $url;

    /**
     * @var string
     */
    private $exportFormat;

    /**
     * @param string $url
     * @param string $exportFormat
     */
    public function __construct(string $url, string $exportFormat)
    {
        $this->url = $url;
        $this->exportFormat = $exportFormat;
    }

    /**
     * Returns Url.
     * The URL for the API specification file.<br><br>**Note:** This URL should be publicly accessible.
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * The URL for the API specification file.<br><br>**Note:** This URL should be publicly accessible.
     *
     * @required
     * @maps url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Export Format.
     * The structure contains API specification formats that Transformer can convert to.
     */
    public function getExportFormat(): string
    {
        return $this->exportFormat;
    }

    /**
     * Sets Export Format.
     * The structure contains API specification formats that Transformer can convert to.
     *
     * @required
     * @maps export_format
     * @factory \ApimaticAPILib\Models\ExportFormats::checkValue
     */
    public function setExportFormat(string $exportFormat): void
    {
        $this->exportFormat = $exportFormat;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['url']           = $this->url;
        $json['export_format'] = ExportFormats::checkValue($this->exportFormat);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
