<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib;

use ApimaticAPILib\Authentication\CustomHeaderAuthenticationCredentialsBuilder;
use ApimaticAPILib\Authentication\CustomHeaderAuthenticationManager;
use ApimaticAPILib\Controllers\ApisManagementController;
use ApimaticAPILib\Controllers\APIValidationExternalApisController;
use ApimaticAPILib\Controllers\APIValidationImportedApisController;
use ApimaticAPILib\Controllers\CodeGenerationExternalApisController;
use ApimaticAPILib\Controllers\CodeGenerationImportedApisController;
use ApimaticAPILib\Controllers\DocsPortalManagementController;
use ApimaticAPILib\Controllers\TransformationController;
use ApimaticAPILib\Utils\CompatibilityConverter;
use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use Unirest\Configuration;
use Unirest\HttpClient;

class ApimaticAPIClient implements ConfigurationInterface
{
    private $apisManagement;

    private $codeGenerationImportedApis;

    private $codeGenerationExternalApis;

    private $transformation;

    private $docsPortalManagement;

    private $aPIValidationImportedApis;

    private $aPIValidationExternalApis;

    private $customHeaderAuthenticationManager;

    private $config;

    private $client;

    /**
     * @see ApimaticAPIClientBuilder::init()
     * @see ApimaticAPIClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->customHeaderAuthenticationManager = new CustomHeaderAuthenticationManager(
            $this->config['authorization'] ?? ConfigurationDefaults::AUTHORIZATION
        );
        $this->client = ClientBuilder::init(new HttpClient(Configuration::init($this)))
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('APIMatic CLI')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::DEFAULT_)
            ->authManagers(['Authorization' => $this->customHeaderAuthenticationManager])
            ->build();
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return ApimaticAPIClientBuilder ApimaticAPIClientBuilder instance
     */
    public function toBuilder(): ApimaticAPIClientBuilder
    {
        $builder = ApimaticAPIClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->httpCallback($this->config['httpCallback'] ?? null);

        $customHeaderAuthentication = $this->getCustomHeaderAuthenticationCredentialsBuilder();
        if ($customHeaderAuthentication != null) {
            $builder->customHeaderAuthenticationCredentials($customHeaderAuthentication);
        }
        return $builder;
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getCustomHeaderAuthenticationCredentials(): CustomHeaderAuthenticationCredentials
    {
        return $this->customHeaderAuthenticationManager;
    }

    public function getCustomHeaderAuthenticationCredentialsBuilder(): ?CustomHeaderAuthenticationCredentialsBuilder
    {
        if (empty($this->customHeaderAuthenticationManager->getAuthorization())) {
            return null;
        }
        return CustomHeaderAuthenticationCredentialsBuilder::init(
            $this->customHeaderAuthenticationManager->getAuthorization()
        );
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see ApimaticAPIClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see ApimaticAPIClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Apis Management Controller
     */
    public function getApisManagementController(): ApisManagementController
    {
        if ($this->apisManagement == null) {
            $this->apisManagement = new ApisManagementController($this->client);
        }
        return $this->apisManagement;
    }

    /**
     * Returns Code Generation Imported Apis Controller
     */
    public function getCodeGenerationImportedApisController(): CodeGenerationImportedApisController
    {
        if ($this->codeGenerationImportedApis == null) {
            $this->codeGenerationImportedApis = new CodeGenerationImportedApisController($this->client);
        }
        return $this->codeGenerationImportedApis;
    }

    /**
     * Returns Code Generation External Apis Controller
     */
    public function getCodeGenerationExternalApisController(): CodeGenerationExternalApisController
    {
        if ($this->codeGenerationExternalApis == null) {
            $this->codeGenerationExternalApis = new CodeGenerationExternalApisController($this->client);
        }
        return $this->codeGenerationExternalApis;
    }

    /**
     * Returns Transformation Controller
     */
    public function getTransformationController(): TransformationController
    {
        if ($this->transformation == null) {
            $this->transformation = new TransformationController($this->client);
        }
        return $this->transformation;
    }

    /**
     * Returns Docs Portal Management Controller
     */
    public function getDocsPortalManagementController(): DocsPortalManagementController
    {
        if ($this->docsPortalManagement == null) {
            $this->docsPortalManagement = new DocsPortalManagementController($this->client);
        }
        return $this->docsPortalManagement;
    }

    /**
     * Returns API Validation Imported Apis Controller
     */
    public function getAPIValidationImportedApisController(): APIValidationImportedApisController
    {
        if ($this->aPIValidationImportedApis == null) {
            $this->aPIValidationImportedApis = new APIValidationImportedApisController($this->client);
        }
        return $this->aPIValidationImportedApis;
    }

    /**
     * Returns API Validation External Apis Controller
     */
    public function getAPIValidationExternalApisController(): APIValidationExternalApisController
    {
        if ($this->aPIValidationExternalApis == null) {
            $this->aPIValidationExternalApis = new APIValidationExternalApisController($this->client);
        }
        return $this->aPIValidationExternalApis;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [Environment::PRODUCTION => [Server::DEFAULT_ => 'https://api.apimatic.io']];
}
