<?php

declare(strict_types=1);

/*
 * ApimaticAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticAPILib;

/**
 * Interface for defining the behavior of Authentication.
 */
interface CustomHeaderAuthenticationCredentials
{
    /**
     * String value for authorization.
     */
    public function getAuthorization(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Auth Header. Provide your Auth key in the format `X-Auth-Key
     *        {auth-key}`.
     */
    public function equals(string $authorization): bool;
}
